### ISSUE TITLE
无法运行，是因为我的python是3.7吗？

### ISSUE THREAD

**Issue by KaiwenTan** [ilusrdbb/guguzhen-loganalysis#1]
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 6.5.0 -- An enhanced Interactive Python.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\parentpoller.py:116: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  ipython-dev@scipy.org""")

runfile('C:/Users/Administrator/Desktop/guguzhen-loganalysis-master/main.py', wdir='C:/Users/Administrator/Desktop/guguzhen-loganalysis-master')
Traceback (most recent call last):

  File "<ipython-input-1-1f709641432e>", line 1, in <module>
    runfile('C:/Users/Administrator/Desktop/guguzhen-loganalysis-master/main.py', wdir='C:/Users/Administrator/Desktop/guguzhen-loganalysis-master')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Administrator/Desktop/guguzhen-loganalysis-master/main.py", line 9, in <module>
    core.start()

  File "C:\Users\Administrator\Desktop\guguzhen-loganalysis-master\core\__init__.py", line 51, in start
    attribute_map = attribute.get_attribute_map(battle_log_str, talent_list, enemy_level)

  File "C:\Users\Administrator\Desktop\guguzhen-loganalysis-master\core\attribute.py", line 21, in get_attribute_map
    _gear_list = gear.get_gear_map_list(gear_list, level_list)

  File "C:\Users\Administrator\Desktop\guguzhen-loganalysis-master\core\gear.py", line 51, in get_gear_map_list
    gear = gear_list[i]

IndexError: list index out of range

**Comment by ilusrdbb** [comment]
是bug，明天修

**Comment by ilusrdbb** [comment]
装备映射问题，修了，再试下 @KaiwenTan
