### ISSUE TITLE
装备名出现问题

### ISSUE THREAD

**Issue by KaiwenTan** [ilusrdbb/guguzhen-loganalysis#2]
奇怪，默认的装备名都会出错，这个要自己调整吗？
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 6.5.0 -- An enhanced Interactive Python.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\parentpoller.py:116: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  ipython-dev@scipy.org""")

runfile('C:/Users/Administrator/Desktop/guguzhen-loganalysis-master/main.py', wdir='C:/Users/Administrator/Desktop/guguzhen-loganalysis-master')
Traceback (most recent call last):

  File "<ipython-input-1-1f709641432e>", line 1, in <module>
    runfile('C:/Users/Administrator/Desktop/guguzhen-loganalysis-master/main.py', wdir='C:/Users/Administrator/Desktop/guguzhen-loganalysis-master')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Administrator/Desktop/guguzhen-loganalysis-master/main.py", line 9, in <module>
    core.start()

  File "C:\Users\Administrator\Desktop\guguzhen-loganalysis-master\core\__init__.py", line 51, in start
    attribute_map = attribute.get_attribute_map(battle_log_str, talent_list, enemy_level)

  File "C:\Users\Administrator\Desktop\guguzhen-loganalysis-master\core\attribute.py", line 17, in get_attribute_map
    gear_list = gear.get_gear_list(battle_log_dom)

  File "C:\Users\Administrator\Desktop\guguzhen-loganalysis-master\core\gear.py", line 16, in get_gear_list
    result_list.append(GEAR_MAP[battle_log_dom.xpath(XPATH_CONFIG['GEAR'])[7]])

KeyError: '萌爪耳钉'

**Comment by ilusrdbb** [comment]
啊，我没想到主题不一样居然会影响导出结果，你可以自己调，修改config.py的GEAR_MAP
稍后我再更新下代码

**Comment by ilusrdbb** [comment]
已提交更新，再试下 @KaiwenTan

**Comment by KaiwenTan** [comment]
> 已提交更新，再试下 @KaiwenTan

KeyError: 'SWORD'
现在是探险者剑出错？不知道怎么了

**Comment by KaiwenTan** [comment]
> 

  File "C:\Users\Administrator\Desktop\guguzhen-loganalysis-master\core\attribute.py", line 21, in get_attribute_map
    _gear_list = gear.get_gear_map_list(gear_list, level_list)

  File "C:\Users\Administrator\Desktop\guguzhen-loganalysis-master\core\gear.py", line 50, in get_gear_map_list
    gear_percent = copy.deepcopy(DEFAULT_GEAR[gear])

KeyError: 'SWORD'

**Comment by ilusrdbb** [comment]
又改了，再试下 @KaiwenTan 
这些问题的原因就是压根没考虑库里会有探险者之剑之类的玩意，我的库数据比较少也测不了（悲

**Comment by KaiwenTan** [comment]
> 又改了，再试下 @KaiwenTan 这些问题的原因就是压根没考虑库里会有探险者之剑之类的玩意，我的库数据比较少也测不了（悲

能运行了，目前没发现问题
